Python/Django/belt_exam/apps/travel/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
url(r'^$', views.index, name="index"),
url(r'^add$', views.add_new_travel, name='add'),  
url(r'^new_create$', views.process_new_travel, name='process_add'),  
url(r'^destination/(?P<travel_id>\d+)$', views.show, name='show'), 
url(r'^(?P<travel_id>\d+)/like$', views.add_to_join, name='join'),             
url(r'^(?P<travel_id>\d+)/unlike$', views.remove_from_join, name='unjoin'),       
url(r'^destroy/(?P<travel_id>\d+)$', views.delete, name='delete'), 

]

Python/Django/belt_exam/apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
url(r'^$', views.index),
url(r'^register$', views.register),    
url(r'^sucess$', views.sucess), 
url(r'^login$', views.login),    
   
    
]

Python/Django/belt_exam/belt_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^travels/', include('apps.travel.urls', namespace='travels')),
    url(r'^', include('apps.users.urls', namespace='user')),
    url(r'^admin/', admin.site.urls),
]

Python/Django/belt_exam/apps/travel/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..users.models import User
from django.db import models
from datetime import date
from datetime import datetime
# Create your models here.
class TravelManager(models.Manager):
    def validate(self, postData):
        errors = {}
       
        if len(postData['destination']) < 1:
            errors["destination"] = "Destination cannot be empty"
        if len(postData['description']) < 1:
            errors["description"] = "Description cannot be empty"
        if postData['date_from'] < postData['date_to']:
                errors["date_from"] = "Travel Date To cannot be before Travel from Date"    
        return errors
    
   
class Travel(models.Model):
    destnation = models.CharField(max_length=255)
    travel_start_date = models.DateField()
    travel_end_date = models.DateField()
    plan = models.TextField()
    travel_created_by = models.ForeignKey(User, related_name="travels_created")
    favorite_travels = models.ManyToManyField(User, related_name="travels_joined")
    objects = TravelManager()

Python/Django/belt_exam/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
class UserManager(models.Manager):
    def validate_registration(self, postData):
        errors = {}
       
        if len(postData['first_name']) < 3:
            errors["first_name"] = "User first name should be more than 2 characters"
        if len(postData['last_name']) < 3:
            errors["last_name"] = "User last name should be more than 2 characters"
        if len(postData['password']) < 8:
            errors["password"] = "password must be at least 8 characters"
        if postData['password'] != postData['password_confirm']:
            errors["password_confirm"] = "passwords do not match"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = "Invalid email"
        else:
            if len(User.objects.filter(email=postData['email'])) > 0:
                errors['email'] = "Email already exists in the system"                                   
        return errors
    def validate_login(self, postData):
        errors = {} 
        if len(postData['password']) < 8:
            errors["password"] = "password must be at least 8 characters"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = "Invalid email"
        else:
            if not len(User.objects.filter(email=postData['email'])) > 0:
                errors['email'] = "Email incorrect"                                   
        return errors
       
class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.TextField()
    objects=UserManager()

Python/Django/belt_exam/apps/travel/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..users.models import User
from .models import Travel
from django.contrib.messages import constants as messages
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect

# Create your views here.
def index(request):
    current_user= User.objects.get(id=request.session['id'])
    travels_user_joined = current_user.travels_joined.all()
    travels_user_not_joined = Travel.objects.exclude(favorite_travels=current_user)
    context = {
        "user":current_user,
        # "travels":Travel.objects.all()
    #     #courses_liked is related name from manytomany
        "travels_joined" : travels_user_joined,
        "other_travels" : travels_user_not_joined
     }
    return render(request, "travel/index.html", context)
def add_new_travel(request):
    
    return render(request, "travel/add_trip.html")

def process_new_travel(request):
    errors = Travel.objects.validate(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect("travels:add")
    if not errors:
        current_user= User.objects.get(id=request.session['id'])  
        new_travel = Travel.objects.create(
        
        destnation=request.POST['destination'],
        travel_start_date=request.POST['date_from'],
        travel_end_date=request.POST['date_to'],
        plan=request.POST['description'],
        travel_created_by=current_user, 
        )
        return redirect("travels:index")
def show(request, travel_id):
    current_travel = Travel.objects.get(id=travel_id)
    context = {
        "travel":current_travel
         }

    return render(request, "travel/show.html", context)
def add_to_join(request, travel_id):
    current_travel = Travel.objects.get(id=travel_id)
    current_user= User.objects.get(id=request.session['id'])  
    current_travel.favorite_travels.add(current_user)
    current_travel.save()
    return redirect("travels:index") 
def remove_from_join(request, travel_id):
    current_travel = Travel.objects.get(id=travel_id)
    current_user= User.objects.get(id=request.session['id'])  
    current_travel.favorite_travels.remove(current_user)
    current_travel.save()
    return redirect("travels:index") 
def delete(request, travel_id):
    travel_delete = Travel.objects.get(id=travel_id)
    travel_delete.delete()
    return redirect("travels:index") 

Python/Django/belt_exam/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import User
from django.contrib.messages import constants as messages
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect
import bcrypt

# Create your views here.
def index(request):
	return render(request, "users/index.html")
def register(request):
    errors = User.objects.validate_registration(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    if not errors:
        hashedpw = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        new_user = User.objects.create(
        
        first_name=request.POST['first_name'],
        last_name=request.POST['last_name'],
        email=request.POST['email'],
        password= hashedpw
        )
        request.session['id'] = new_user.id    
    return redirect('travels:index')
def login(request):
    errors = User.objects.validate_login(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    if not errors:
            user = User.objects.filter(email=request.POST['email'])[0]
            request.session['id'] = user.id
            if  bcrypt.checkpw(request.POST['password'].encode(), user.password.encode()):
                return redirect('travels:index')
            else:
                messages.error(request, 'password is incorrect.') 
                return redirect('/')                      
def sucess(request):
    context = {
        'user': User.objects.get(email=request.session['emailuser'])
    }
    return render(request, "users/sucess.html", context)

Python/Django/belt_exam/apps/travel/templates/travel/add_trip.html
<h1>Add a Trip</h1>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form action="{% url 'travels:process_add' %}" method='POST'> 
    {% csrf_token %}
    <ul>
        Destination: <input type="text" name= "destination">
        Description: <input type="textarea" name="description">
        Travel Date From: <input type="date" name="date_from">
        Travel Date To: <input type="date" name="date_to">
        
        <input type="submit" value="Add"> 
    </ul>
</form> 
<a href="{% url 'travels:index' %}">Home</a>
<a href="/">Logout</a>

Python/Django/belt_exam/apps/travel/templates/travel/index.html
<h2>Hello, {{user.first_name}}</h2>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h3>Your Trip Schedules</h3>
<table> 
    <thead>
        <tr>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date</th>
            <th>Plan</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for travel in travels_joined %}
            <tr>
                <td><a href="{% url 'travels:show' travel.id %}">{{ travel.destnation}}</a></td>
                <!-- <td>{{ travel.destnation}}</td> -->
                <td>{{ travel.travel_start_date}}</td>
                <td> {{ travel.travel_end_date}}</td>
                <td>{{ travel.plan }} </td>
                <td><a href="{% url 'travels:unjoin' travel.id %}">remove from join</a></td>
                
            </tr>
        {% endfor %}
    </tbody>
</table>
<h3>Other Users Travel Plans</h3>
<table> 
    <thead>
        <tr>
            <th>Name</th>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date</th>
            <th>Do you want to join?</th>
        </tr>
    </thead>
    <tbody>
        {% for travel in other_travels %}
            <tr>
                <td>{{travel.travel_created_by.first_name}}</td> 
                <td><a href="{% url 'travels:show' travel.id %}">{{ travel.destnation}}</a></td>
                <td>{{ travel.travel_start_date}}</td>
                <td> {{ travel.travel_end_date}}</td>
                <td><a href="{% url 'travels:join' travel.id %}">join</a></td>
                <td><a href="{% url 'travels:delete' travel.id %}">delete</a></td>
                
            </td>
              
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'travels:add' %}">Add Travel Plan</a></td>
<a href="/">Logout</a>

Python/Django/belt_exam/apps/travel/templates/travel/show.html
<h3>{{travel.destnation}}</h3>
<p>Planned by: {{travel.travel_created_by.first_name}}</p>
<p>Travel Date From: {{travel.travel_start_date}}</p>
<p>Travel Date To: {{travel.travel_end_date}}</p>

<h4>Other users joining the trip:</h4>
<ul>
    {% for user in travel.favorite_travels.all %}
    <li>{{user.first_name}}</li>
    {% endfor %}
</ul>

<a href="{% url 'travels:index' %}">Home</a>
<a href="/">Logout</a>