Python/Django/courses/apps/new_courses/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
url(r'^$', views.index, name="index"),
url(r'^new_create$', views.add_new_course, name='add'),  
url(r'^(?P<course_id>\d+)$', views.show, name='show'),       
url(r'^(?P<course_id>\d+)/like$', views.add_to_favorites, name='like'),       
url(r'^(?P<course_id>\d+)/unlike$', views.remove_from_favorites, name='unlike'),       
url(r'^destroy/(?P<course_id>\d+)$', views.delete, name='delete'), 
# url(r'^delete_course/(?P<course_id>\d+)$', views.delete_course, name='delete_course'),   

]

Python/Django/courses/apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
url(r'^$', views.index),
url(r'^register$', views.register),    
url(r'^sucess$', views.sucess), 
url(r'^login$', views.login),    
   
    
]

Python/Django/courses/courses/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^courses/', include('apps.new_courses.urls', namespace='courses')),
    url(r'^', include('apps.users.urls', namespace='user')),
    url(r'^admin/', admin.site.urls)
]

Python/Django/courses/apps/new_courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..users.models import User
from django.db import models

# Create your models here.
class CourseManager(models.Manager):
    def validate(self, postData):
        errors = {}
       
        if len(postData['course_name']) < 5:
            errors["course_name"] = "Course name should be more than 5 characters"
        if len(postData['description']) < 5:
            errors["description"] = "Description should be more than 5 characters"
              
        return errors
    
   
class Course(models.Model):
    course_name = models.CharField(max_length=255)
    description = models.TextField()
    course_created_by = models.ForeignKey(User, related_name="courses_created")
    favorite_courses = models.ManyToManyField(User, related_name="courses_liked")
    created_at = models.DateTimeField(auto_now_add = True)
    objects = CourseManager()

Python/Django/courses/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
class UserManager(models.Manager):
    def validate_registration(self, postData):
        errors = {}
       
        if len(postData['first_name']) < 2:
            errors["first_name"] = "User first name should be more than 2 characters"
        if len(postData['last_name']) < 2:
            errors["last_name"] = "User last name should be more than 2 characters"
        if len(postData['password']) < 8:
            errors["password"] = "password must be at least 8 characters"
        if postData['password'] != postData['password_confirm']:
            errors["password_confirm"] = "passwords do not match"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = "Invalid email"
        else:
            if len(User.objects.filter(email=postData['email'])) > 0:
                errors['email'] = "Email already exists in the system"                                   
        return errors
    def validate_login(self, postData):
        errors = {} 
        if len(postData['password']) < 8:
            errors["password"] = "password must be at least 8 characters"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = "Invalid email"
        else:
            if not len(User.objects.filter(email=postData['email'])) > 0:
                errors['email'] = "Email incorrect"                                   
        return errors
       
class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.TextField()
    objects=UserManager()

Python/Django/courses/apps/new_courses/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..users.models import User
from .models import Course
from django.contrib.messages import constants as messages
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect


# Create your views here.
def index(request):
    current_user= User.objects.get(id=request.session['id'])
    courses_user_liked = current_user.courses_liked.all()
    courses_user_not_liked = Course.objects.exclude(favorite_courses=current_user)
    context = {
        "user":current_user,
        #courses_liked is related name from manytomany
        
        "courses_liked" : courses_user_liked,
        "other_courses" : courses_user_not_liked
     }
    return render(request, "new_courses/index.html", context)

def add_new_course(request):
    errors = Course.objects.validate(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect("travels:add")
    if not errors:
        current_user= User.objects.get(id=request.session['id'])  
        new_course = Course.objects.create(
        #blue in db
        # after request.post in form  
        # course_created_by is foreignKey name from one to many relations 
        course_name=request.POST['course_name'],
        description=request.POST['description'],
        course_created_by=current_user, 
        )
        return redirect("courses:index")
def show(request, course_id):
    current_course = Course.objects.get(id=course_id)
    context = {
        "course":current_course
    }
    return render(request, "new_courses/show.html", context)
def add_to_favorites(request, course_id):
    current_course = Course.objects.get(id=course_id)
    current_user= User.objects.get(id=request.session['id'])  
    current_course.favorite_courses.add(current_user)
    current_course.save()
    return redirect("courses:index") 
def remove_from_favorites(request, course_id):
    current_course = Course.objects.get(id=course_id)
    current_user= User.objects.get(id=request.session['id'])  
    current_course.favorite_courses.remove(current_user)
    current_course.save()
    return redirect("courses:index") 
# def delete(request, course_id):
#      context = {
#          #blue id = database
#          #yellow id = in function def id
#          "new_courses": Course.objects.get(id=course_id)
#      }
#      return render(request, "new_courses/delete.html", context)
def delete(request, course_id):
    course_delete = Course.objects.get(id=course_id)
    course_delete.delete()
    return redirect("courses:index") 

Python/Django/courses/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import User
from django.contrib.messages import constants as messages
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect
import bcrypt

# Create your views here.
def index(request):
	return render(request, "users/index.html")
def register(request):
    errors = User.objects.validate_registration(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    if not errors:
        hashedpw = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        new_user = User.objects.create(
        
        first_name=request.POST['first_name'],
        last_name=request.POST['last_name'],
        email=request.POST['email'],
        password= hashedpw
        )
        request.session['id'] = new_user.id    
    return redirect('courses:index')
def login(request):
    errors = User.objects.validate_login(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    if not errors:
            user = User.objects.filter(email=request.POST['email'])[0]
            request.session['id'] = user.id
            if  bcrypt.checkpw(request.POST['password'].encode(), user.password.encode()):
                return redirect('courses:index')
            else:
                messages.error(request, 'password is incorrect.') 
                return redirect('/')                      
def sucess(request):
    context = {
        'user': User.objects.get(email=request.session['emailuser'])
    }
    return render(request, "users/sucess.html", context)

Python/Django/courses/apps/new_courses/templates/new_courses/delete.html
<h1>Are you sure you want to delete the following courses</h1>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <!-- new_courses is what i called in the query under delete -->
    <p>name: {{new_courses.course_name}}</p>
    <p>description: {{new_courses.description}}</p>
    <a href="/">No</a>
<form action="/courses/delete_course/{{new_courses.id }}" method='post'> 
    {% csrf_token %}
    <ul>
      <input type="submit" name = "yes" value ="Yes! I want to delete" >
       
    </ul>
</form> 

Python/Django/courses/apps/new_courses/templates/new_courses/index.html
<h1>Add a new course</h1>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form action="{% url 'courses:add' %}" method='POST'> 
    {% csrf_token %}
    <ul>
        Name: <input type="text" name= "course_name">
        Description: <input type="textarea" name="description">
        <input type="submit" value="Add"> 
    </ul>
</form> 
<h1>courses</h1>
<h2>welcome {{user.first_name}}</h2>
<table> 
    <thead>
        <tr>
            <th>Course Name</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Made By</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
       
        {% for course in other_courses %}
            <tr>
                <td>{{ course.course_name }}</td>
                <td>{{ course.description}}</td>
                <td> {{ course.created_at }}</td>
                <td>{{course.course_created_by.first_name}}</td>
                {% if user.id == course.course_created_by.id %}
                <td><a href="/courses/destroy/{{ course.id }}">delete</a></td>
                <td><a href="{% url 'courses:show' course.id %}">show</a></td>
                <td><a href="{% url 'courses:like' course.id %}">add to favorites</a></td>
                {% else %}
                <td><a href="{% url 'courses:show' course.id %}">show</a></td>
                <td><a href="{% url 'courses:like' course.id %}">add to favorites</a></td>
               {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
<table> 
    <thead>
        <tr>
            <th>Course Name</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Made By</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
<h1>favorites</h1>
        {% for course in courses_liked %}
            <tr>
                <td>{{ course.course_name }}</td>
                <td>{{ course.description}}</td>
                <td> {{ course.created_at }}</td>
                <td>{{course.course_created_by.first_name}}</td>
                {% if user.id == course.course_created_by.id %}
                <td><a href="/courses/destroy/{{ course.id }}">delete</a></td>
                <td><a href="{% url 'courses:show' course.id %}">show</a></td>
                <td><a href="{% url 'courses:unlike' course.id %}">remove from favorites</a></td>
                {% else %}
                <td><a href="{% url 'courses:show' course.id %}">show</a></td>
                <td><a href="{% url 'courses:unlike' course.id %}">remove from favorites</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>

Python/Django/courses/apps/new_courses/templates/new_courses/show.html
<h1>{{course.course_name}}</h1>
<ul>
    {% for user in course.favorite_courses.all %}
    <li>{{user.first_name}}</li>
    {% endfor %}
</ul>